name: Sync with vLLM main

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/LukasBluebaum/Test-Repo2.git

      - name: Fetch upstream changes
        run: git fetch upstream main

      - name: Create a new branch with upstream changes
        id: create_branch
        run: |
          BRANCH_NAME="sync/vllm-main-$(date +%Y-%m-%d)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git branch -D $BRANCH_NAME || true
          git checkout -b $BRANCH_NAME upstream/main

      - name: Push the new branch to the fork
        run: |
          git push -u origin ${{ env.BRANCH_NAME }} --force

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Sync with vllm-project/vllm main on $(date +%Y-%m-%d)" \
            --body "This PR was automatically created to sync changes from \`vllm-project/vllm\`'s main branch." \
            --base main \
            --head ${{ env.BRANCH_NAME }}
